config/routes.rb
Rails.application.routes.draw do
  
  get    "login"  => "sessions#new"
  post   "login"  => "sessions#create"
  delete "logout" => "sessions#destroy"
  get 'home/index'
  get 'books/thongbao'
  get  "resigter" => "users#new"
  get  "addbook" => "books#new"
  get '/button', to: 'favorites#button', as: 'button'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)


root 'books#index'
  
  resources :books do

  resources :reviews
  resources :comments
  resources :bookfavorites
  end


  resources :users do
  resources :bookfavorites 
  end 
  resources :requires

end

app/models/comment.rb
class Comment < ApplicationRecord
belongs_to :book
belongs_to :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	 protect_from_forgery with: :exception
	 include SessionsHelper   
    
    before_action :require_login
		before_action :find_book
    before_action :find_comment,only: [ :destroy]

    def new 
       @comment = Comment.new 
    end

    def create
      @comment = Comment.new(comment_params)
      @comment.book_id = @book.id
      @comment.user_id = @current_user.id
       if @comment.save
        redirect_to book_path(@book)
    end
   end

   def edit
   end
   
   def destroy
     @comment.destroy
     redirect_to book_path(@book)
    end   
    
    private

		def comment_params
			params.require(:comment).permit(:comment)
		end

		def find_book
			@book = Book.find(params[:book_id])
		end
   	def find_comment
      @comment = Comment.find(params[:id])
    end
    end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb

	<ul class="comment__list">
		<li>
			<div class="wn__comment">
				<div class="thumb">
				<img src="<%= comment.user.user_img.url(:user_index) %>" alt="">
				</div>
				<div class="content">
					<div class="comnt__author d-block d-sm-flex">
						<span><a href="<%= user_path(comment.user)%>"><%= comment.user.name %></a> Post author</span>
						<span>
							<% if comment.created_at > Time.now.beginning_of_day %>
								Vào <%="#{time_ago_in_words(comment.created_at)} ago"%>
							<% else %>
								Vào <%= l(comment.created_at,format: '%B, %d %Y %H:%M:%S')  %>
							<% end %>
						</span>
						<% if  logged_in? %>
						<% if @current_user.id == comment.user_id %>
							<div class="reply__btn">
							<%= link_to "Delete", book_comment_path(comment.book, comment), method: :delete, data: { confirm: "Are you sure?" }, class: "" %>
							</div>
						<% end %>
						<% end %>
						<% from_reply_form ||= nil %>
						<% unless from_reply_form %> 
							<div class="reply__btn">
								<%= link_to 'Reply', new_book_comment_path(comment.book,comment.id) %>
							</div>
						<% end %>
					</div>
					<p><%= comment.comment %></p>
				</div>
			</div>
		</li>
	</ul>