config/routes.rb
Rails.application.routes.draw do
  
  get    "login"  => "sessions#new"
  post   "login"  => "sessions#create"
  delete "logout" => "sessions#destroy"
  get 'home/index'
  get 'books/thongbao'
  get  "resigter" => "users#new"
  get  "addbook" => "books#new"
  get '/button', to: 'favorites#button', as: 'button'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)


root 'books#index'
  
  resources :books do

  resources :reviews
  resources :comments
  resources :bookfavorites
  end


  resources :users do
  resources :bookfavorites 
  end 
  resources :requires

end

app/models/require.rb
class Require < ApplicationRecord
 belongs_to :user,optional: true

end

app/controllers/requires_controller.rb
class RequiresController < ApplicationController
protect_from_forgery with: :exception
  include SessionsHelper
    before_action :require_admin, only:[ :index, :show,:edit, :update, :destroy]
    before_action :find_book, only:[:show, :edit, :update, :destroy]
   def index
   	 @books = Require.all
   end

   def new 
      @book = Require.new
      @book.user_id = current_user.id
   end

   def create

      @book = Require.new(require_params)
      @book.user_id = current_user.id
      if @book.save
         flash[:success] = "Thêm mới yêu cầu thành công, admin sẽ cố gắng xử lý yêu cầu của bạn trong thời gian sớm nhất"
         redirect_to root_path
      else
        flash[:danger] = "Thêm mới yêu cầu thất bại"
      end    
   end

   def destroy 
      @book.destroy
      flash[:info] = "xóa yêu cầu thành công"
      redirect_to requires_path 
   end
   
   private
   def require_params
       params.require(:require).permit(:title, :description, :author, :comment, :user_id)   
   end
   def find_book
         @book = Require.find(params[:id])
   end    
end

app/helpers/requires_helper.rb
module RequiresHelper
end

app/views/requires/_form.html.erb
<%= simple_form_for @book, :html => { :multipart => true } do |f| %>
	<%= f.input :title, label: "Book Title" %>
	<%= f.input :description %>
	<%= f.input :author %>
	<%= f.input :comment %>
	<%= f.button :submit, :class => 'btn-custom2' %>
<% end %>

app/views/requires/index.html.erb

<% if @books.count == 0 %>
<h1> không có yêu cầu nào  </h1>

<% else %> 

<div class="row">

  <table class="table table-hover">
    <thead>
      <tr>
        <th>Book's Name</th>
        <th>Author</th>
        <th>Book's Description</th>
        <th>Comment</th>
        <th>Request By</th>
        <th>Time Requested</th>

      </tr>
    </thead>
    <tbody>

  <% @books.each do |r| %>
    <tr>
      <td>
        <a href="/requires/<%=r.id %>"><%= r.title %></a>
      </td>
      <td><%= r.author %></td>
      <td><%= r.description %></td>
      <td><%= r.comment %></td>
      <td><%= r.user.name %></td>
      <td><%= "#{time_ago_in_words(r.created_at)} ago"%></td>
    </tr>
<% end %>
    </tbody>

</table>
</div>

<% end %>	


app/views/requires/new.html.erb
<h1>Yêu cầu mới</h1>
<%= render 'form' %>


app/views/requires/show.html.erb
<div class="row">
	<div class="col-md-4">
	  <img src="assets/icon.png"  class="book" >
	</div>

	<div class="col-md-8">
		<h2><%= @book.title %></h2>
		<h3><%= @book.author %></h3>
		<p><%= @book.description %></p>
		<p><%= @book.comment %></p>
	</div>
</div>

<div class="row">
	<div class="col-md-4">
	</div>
</div>

 <% if admin? %>
 <%= link_to 'Delete', require_path(@book), method: :delete, data: {confirm: "are you sure"}  %>
 <% end %>