config/routes.rb
Rails.application.routes.draw do
  
  get    "login"  => "sessions#new"
  post   "login"  => "sessions#create"
  delete "logout" => "sessions#destroy"
  get 'home/index'
  get 'books/thongbao'
  get  "resigter" => "users#new"
  get  "addbook" => "books#new"
  get '/button', to: 'favorites#button', as: 'button'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)


root 'books#index'
  
  resources :books do

  resources :reviews
  resources :comments
  resources :bookfavorites
  end


  resources :users do
  resources :bookfavorites 
  end 
  resources :requires

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
protect_from_forgery with: :exception
 include SessionsHelper

    before_action :require_login
	before_action :find_book
	before_action :find_review, only: [:edit, :update, :destroy]

	def new
		@review = Review.new
	end

	def create
		@review = Review.new(review_params)
		@review.book_id = @book.id
		@review.user_id = current_user.id

		if @review.save
			redirect_to book_path(@book)
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @review.update(review_params)
			redirect_to book_path(@book)
		else
			render 'edit'
		end
	end

	def destroy
		@review.destroy
		redirect_to book_path(@book)
	end

	private

		def review_params
			params.require(:review).permit(:rating, :comment)
		end

		def find_book
			@book = Book.find(params[:book_id])
		end

		def find_review
			@review = Review.find(params[:id])
		end

end

app/helpers/reviews_helper.rb
module ReviewsHelper
    include SessionsHelper
end

app/views/reviews/_form.html.erb

<%= simple_form_for([@book, @book.reviews.build]) do |f| %>
	<div class="review_form_field">
		<div class="input__box">
			<%= f.input  :rating %>
		</div>
		<div class="input__box">
			<%= f.input  :comment %>
		</div>
		<div class="review-form-actions">
		<%= f.button :submit, :class => "" %>
		</div>
	</div>
<% end %>


<script>
	$('#rating-form').raty({
		path: '/assets/',
		scoreName: 'review[rating]'
	});
</script>

app/views/reviews/_review.html.erb

	<div>
		<a href="#">
			<img class="profile-images1" src="<%= review.user.user_img.url(:user_index)%>" alt="...">
			<h4><%= review.user.name %></h4>
		</a>
		
		<div class="review__ratings__type d-flex">
			<div class="review-ratings">
				<div class="rating-summary d-flex">
					<span>Rating</span>
					<input type="hidden" class="rating" data-filled="glyphicon glyphicon-star" value=<%= review.rating %> data-empty="glyphicon glyphicon-star-empty"/>
				</div>
				<div class="rating-summary d-flex">
					<% if logged_in? %>
					<% if review.user_id == current_user.id %>
							<div class="links btn-group">
								<%= link_to "Edit", edit_book_review_path(review.book, review), class: "btn btn-custom" %>
								<%= link_to "Delete", book_review_path(review.book, review), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-custom" %>
							</div>
						<% end %>	
					<% end %>
				</div>
			</div>
			<div class="review-content">
				<p><%= review.comment %></p>
				<p>
					<% if review.created_at > Time.now.beginning_of_day %>
						Vào <%="#{time_ago_in_words(review.created_at)} ago"%> 
				  	<% end %>
				</p>
			</div>
		</div>
	</div>

app/views/reviews/edit.html.erb

<h1>Edit Review</h1>
<%= simple_form_for([@book, @review]) do |f| %>
	<div class="review_form_field">
		<div class="input__box">
			<%= f.input  :rating %>
		</div>
		<div class="input__box">
			<%= f.input  :comment %>
		</div>
		<div class="review-form-actions">
		<%= f.button :submit, :class => "" %>
		</div>
	</div>
<% end %>



<script>
	$('#rating-form').raty({
		path: '/assets/',
		scoreName: 'review[rating]'
	});
</script>

app/views/reviews/new.html.erb
<div class="review-fieldset">
	<h2>You're reviewing:</h2>
	<%= render 'form' %>
</div>