config/routes.rb
Rails.application.routes.draw do
  
  get    "login"  => "sessions#new"
  post   "login"  => "sessions#create"
  delete "logout" => "sessions#destroy"
  get 'home/index'
  get 'books/thongbao'
  get  "resigter" => "users#new"
  get  "addbook" => "books#new"
  get '/button', to: 'favorites#button', as: 'button'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)


root 'books#index'
  
  resources :books do

  resources :reviews
  resources :comments
  resources :bookfavorites
  end


  resources :users do
  resources :bookfavorites 
  end 
  resources :requires

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  has_many :reviews
  has_many :comments
  has_many :bookfavorites
	belongs_to :category, optional: true

	has_attached_file :book_img, :styles => { :book_index => "250x350>", :book_show => "325x475>" }, :default_url => "assets/default1.jpg"
  validates_attachment_content_type :book_img, :content_type => /\Aimage\/.*\Z/
  
  def self.search(search)
  if search

    where('title LIKE ?', "%#{search}%").order('id DESC')
  else
    order('id DESC') 
  end
  end
  
end

app/models/bookfavorite.rb
class Bookfavorite < ApplicationRecord
belongs_to :book
belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :books

end

app/models/comment.rb
class Comment < ApplicationRecord
belongs_to :book
belongs_to :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
end

app/models/require.rb
class Require < ApplicationRecord
 belongs_to :user,optional: true

end

app/models/review.rb
class Review < ApplicationRecord
belongs_to :book
belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord

	  validates :name, format: { without: /\s/ }, uniqueness: true, presence: true, length: { maximum: 10 }, if: :can_validate
	  validates :email, uniqueness: true, presence: true, if: :can_validate, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }, if: :can_validate
  	 def can_validate
    	true
  	end

    has_many :requires
    has_many :reviews
    has_many :comments
    has_many :bookfavorites
	has_secure_password

	has_attached_file :user_img, :styles => { :user_index => "250x350>", :user_show => "325x475>" }, :default_url => "default.png"
  	validates_attachment_content_type :user_img, :content_type => /\Aimage\/.*\Z/

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    protect_from_forgery with: :exception
    include SessionsHelper
    before_action :require_admin, only:[:new,:create,:edit, :update, :destroy]  
  	before_action :find_book, only:[:show, :edit, :update, :destroy]
    def index
        if params[:category].blank?
      	@book = Book.all.order("created_at DESC")
        else
         @category_id = Category.find_by(name: params[:category]).id
         @book = Book.where(:category_id => @category_id).order("created_at DESC")
        end
        if !params[:search].blank?
        @book = Book.search(params[:search])
        end  
    end 
    
    def new
      	@book = Book.new
        @categories = Category.all.map{|c| [c.name, c.id] }  
    end  		
    
    def show
      if @book.reviews.blank?
      @average_review = 0
    else
      @average_review = @book.reviews.average(:rating).round(2)
    end
    end

    def create
      	@book = Book.new(book_params)
        @book.category_id = params[:category_id]
      	if @book.save
      	   flash[:success] = "Thêm mới sách thành công"
           redirect_to root_path
      	else
      	   flash[:danger] = "Thêm mới sách thất bại" 
      	end      
    end

    def edit
        @categories = Category.all.map{|c| [c.name, c.id] }  
    end
    
    def update
        @book.category_id = params[:category_id]
         if @book.update(book_params)
            redirect_to book_path(@book)
         else
            render 'edit' 
         end
    end         

    def destroy
        @book.destroy
        flash[:success] = "xóa sách thành công" 
        redirect_to root_path
    end
    
    private
    def book_params
      params.require(:book).permit(:title, :description, :author, :category_id, :book_img, :search)
    end
    
    def find_book
        @book = Book.find(params[:id])
    end         	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 protect_from_forgery with: :exception
 include SessionsHelper
 include BookfavoritesHelper
  
 before_action :require_login, only:[:index, :show, :edit, :update]
 before_action :find_user_by_id, only:[:show, :edit, :update, :destroy]

  def index

  end
   
  def new
      @user = User.new
  end
  
  def show
    check @user
    @book = Book.where(:id => @id).order("created_at DESC") 
  end

  def create
      @user = User.new (user_params)
      if @user.save
      flash[:success] = "Đăng ký thành công"  
      redirect_to login_path
      else
        flash[:danger] = "Đăng ký thất bại !"
        render :new
      end
  end

  def edit
  end  
  
  def update
      if @user.update(user_params)
          redirect_to user_path(@user)
      else
          render 'edit' 
      end
  end    

  private
  def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :user_img)
  end
  def find_user_by_id
      @user = User.find(params[:id])
  end     
end

app/helpers/application_helper.rb
module ApplicationHelper

    include SessionsHelper
end

app/helpers/bookfavorites_helper.rb
module BookfavoritesHelper
     def check user
     @bookfavorite = Bookfavorite.where(:user_id => @user.id)
     @id = @bookfavorite
    end
end

app/helpers/books_helper.rb
module BooksHelper
include SessionsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/requires_helper.rb
module RequiresHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
    include SessionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

      def log_in user
        session[:user_id] = user.id
      end

      def log_out
        session.delete :user_id
      end
    # Returns the current logged-in user (if any).
      def current_user
        @current_user ||= User.find_by id: session[:user_id]
      end

    # Check user has logged in before ? 
      def logged_in?
        current_user.present?
      end
      
      def require_login
          unless logged_in?
           flash[:danger] = "bạn phải truy cập trước khi thực hiện tác vụ này !" 
           redirect_to login_path
          end
      end

      def require_admin
          unless admin?
          flash[:warning] = "bạn không có quyền thực hiện tác vụ này !"  
          redirect_to root_path     
          end
      end   
      
      def admin?
          if logged_in?
              current_user.admin 
          else 
             return false    
          end
      end 

    end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project2</title>
    <%= csrf_meta_tags %>
    	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		
		<!-- Google font (font-family: 'Roboto', sans-serif; Poppins ; Satisfy) -->
		<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800" rel="stylesheet"> 
		<link href="https://fonts.googleapis.com/css?family=Poppins:300,300i,400,400i,500,600,600i,700,700i,800" rel="stylesheet">
		<link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900" rel="stylesheet"> 
	  
  </head>

  <body class="all">
  <div class="wrapper" id="wrapper">
  <!-- Header -->
  <header id="wn__header" class="header__area header__absolute sticky__header">
	  <div class="container-fluid">
		  <div class="row">
			  <div class="col-md-6 col-sm-6 col-6 col-lg-2">
				  <div class="logo">
				  	<%= link_to image_tag("logo.png", :border=>0), root_path, class: "navbar-brand" %>
				  </div>
			  </div>
			  <div class="col-lg-8 d-none d-lg-block">
				  <nav class="mainmenu__nav">
					  <ul class="meninmenu d-flex justify-content-start">
							<li class="drop with--one--item">
							<%= link_to "Home", root_path %>
							</li>
						  <li class="drop">
							  <a href="#"  data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Books <span class="caret"></span></a>
							  <div class="megamenu dropdown">
								  <ul class="item item01">
									  <li class="title">Categories</li>
										<% Category.all.each do |category| %>
											<li>
											<%= link_to category.name, books_path(category: category.name), class: "link" %> 
											</li>  
										<% end %> 
								  </ul>
							  </div>
						  </li>
						<li><a href="contact.html">Contact</a></li>
					  </ul>
				  </nav>
			  </div>
			  <div class="col-md-6 col-sm-6 col-6 col-lg-2">
				  <ul class="header__sidebar__right d-flex justify-content-end align-items-center">
				  		<! SEARCH !>
				  		<li class="shop_search">
							<form class="navbar-form navbar-left">
								<%= form_tag(books_path, :method => "get", id: "search-form") do %>
									<ul class="header__sidebar__right d-flex justify-content-end align-items-center">
										<li class="shop_search">
											<%= text_field_tag :search, params[:search], placeholder: "Type anything here" , class: 'form-control'%>
										</li>
										<li class="shop_search">
											<%= submit_tag "Search", :name => nil , class: 'btn btn-default'%>
										</li>
									</ul>
								<% end %>                               
							</form>
						</li>
						<% if logged_in? %>
							<li class="setting__bar__icon">
								<nav class="mainmenu__nav">
									<ul class="meninmenu d-flex justify-content-start">
										<! NOTI !>
										<li class="drop">
											<button class="btn btn-default btn-lg btn-link" style="font-size:23px;    color: white;">
												<span class="glyphicon glyphicon-bell"></span>
											</button>
											<span class="badge badge-notify">3</span>
											<div class="megamenu mega02">
												<ul class="item item01 ">
													<li class="title">USER</li>
													<li>
														<div class="media">
															<div class="media-left">
																<a href="#">
																ABC
																</a>
															</div>
															<div class="media-body">
																<h4 class="media-heading">XYZ</h4>
																MLH
															</div>
														</div>                 
													</li>
												</ul>
											</div>
										</li>
										<! // NOTI !>
										<! USER !>
										<li class="drop">
											<a href="#"  data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
												<img class="avatar" alt="<%= @current_user.name %>" src="<%= @current_user.user_img.url(:user_index) %>">
											</a>
											<div class="megamenu mega01">
												<ul class="item item01 ">
													<li class="title">Setting</li>
													<li>
														<div class="media">
															<div class="media-left">
																<a href="#">
																<img class="profile-images1" class="media-object" src="<%= @current_user.user_img.url(:user_index) %>" alt="...">
																</a>
															</div>
															<div class="media-body">
																<h4 class="media-heading"><%= @current_user.name %></h4>
																<%= @current_user.email %>
															</div>
														</div>                 
													</li>
													<li>
														<div class="row">
															<div class="col-sm-4 col-md-4">
																<p>

																<% if !admin? %>
																<a href="<%=new_require_path%>" class="btn btn-primary"  role="button">yêu cầu sách</a>
																<% else %>
																<a href="<%=requires_path%>" class="btn btn-primary"  role="button">yêu cầu sách</a>
																<% end %>
																	<a href="<%=edit_user_path(@current_user)%>" class="btn btn-primary"  role="button">cài đặt</a> 
																	<a href="<%=user_path(@current_user)%>" class="btn btn-primary" role="button">Profile</a> 
																</p>
															</div>
														</div>
													</li>
													
													<li>
														<%= link_to  "Log out", logout_path, method: :delete,  class: "text btn btn-danger" %>
													</li> 
												</ul>
											</div>
										</li>
										<! // USER !>
									</ul>
								</nav>
							</li>
							<% if admin? %>
								<li><%= link_to "Addbook", new_book_path %></li>
							<% end %> 
						<% else %> 
							<li class="drop with--one--item">
								<%= link_to "Resigter", new_user_path %>
							</li>
							<li class="drop with--one--item">
								<%= link_to "Login", login_path %>
							</li>
						<% end %> 

				  </ul>
			  </div>
		  </div>

	  </div>		
  </header>

      <!hiện thông báo đăng nhập!>
    <section class="content" style="min-height: 170px;">
      <% flash.each do |key, value| %>
        <div class="row">
          <div class="alert alert-<%= key %>">
            <%= value %>

          </div>
        </div>
      <% end %>
    </section>

    <div class="container">
    <%= yield %>
  </div>


  </body>
</html>